'use strict';

const envelopeSchema = {
  ok: 'boolean',
  data: 'object|null',
  error: 'object|null',
  meta: 'object',
};

const capabilities = {
  auth: {
    id: 'auth',
    summary: 'Manage Microsoft Graph browser-session authentication',
    description: 'Authenticate with Microsoft Edge through the Playwright persistent-context flow and inspect cached Graph and Outlook tokens.',
    verbs: {
      login: {
        id: 'auth.login',
        summary: 'Authenticate to Microsoft 365 and capture Graph/Outlook/Chat tokens',
        method: 'AUTH',
        auth: 'none',
        handler: 'graph-auth',
        params: [
          { name: 'force', type: 'boolean', required: false, doc: 'Force visible login by passing --force' },
          { name: 'verbose', type: 'boolean', required: false, doc: 'Print per-phase progress to stderr' },
        ],
        output: { envelope: envelopeSchema, data: 'Captured token presence, channel-message scope status, and scope counts' },
        examples: ['mg-api auth login', 'mg-api auth login --force', 'mg-api auth login --verbose'],
      },
      logout: {
        id: 'auth.logout',
        summary: 'Clear the saved browser profile and auth file',
        method: 'AUTH',
        auth: 'none',
        handler: 'graph-auth',
        params: [],
        output: { envelope: envelopeSchema, data: 'Logout status' },
        examples: ['mg-api auth logout'],
      },
      status: {
        id: 'auth.status',
        summary: 'Report whether cached Graph/Outlook auth exists',
        method: 'LOCAL',
        auth: 'none',
        handler: 'auth-status',
        params: [],
        output: { envelope: envelopeSchema, data: 'Auth file location and presence of each token' },
        examples: ['mg-api auth status'],
      },
    },
  },
  email: {
    id: 'email',
    summary: 'Read and send Outlook mail',
    description: 'List, read, send, reply, search, move, delete messages and inspect attachments.',
    verbs: {
      list: {
        id: 'email.list',
        summary: 'List messages from the signed-in mailbox',
        method: 'GET',
        path: '/me/messages',
        token: 'graph',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'top', type: 'number', required: false, default: 25, doc: 'Maximum messages to return' },
          { name: 'filter', type: 'string', required: false, doc: 'OData $filter expression, for example "isRead eq false"' },
          { name: 'select', type: 'string', required: false, doc: 'Comma-separated OData $select fields' },
          { name: 'orderby', type: 'string', required: false, doc: 'OData $orderby expression, for example "receivedDateTime desc"' },
        ],
        query: { '$top': '{top}', '$filter': '{filter}', '$select': '{select}', '$orderby': '{orderby}' },
        output: { envelope: envelopeSchema, data: 'Message collection' },
        examples: ['mg-api email list --top 10 --select subject,from,receivedDateTime --orderby "receivedDateTime desc"'],
      },
      get: {
        id: 'email.get',
        summary: 'Get a single message by id',
        method: 'GET',
        path: '/me/messages/{message-id}',
        token: 'graph',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'message-id', type: 'string', required: true, doc: 'Message id' },
          { name: 'select', type: 'string', required: false, doc: 'Comma-separated OData $select fields' },
        ],
        query: { '$select': '{select}' },
        output: { envelope: envelopeSchema, data: 'Single message' },
        examples: ['mg-api email get --message-id AAMkAGI... --select subject,body,from'],
      },
      send: {
        id: 'email.send',
        summary: 'Send a message via the Outlook REST API',
        method: 'POST',
        path: '/me/sendmail',
        token: 'outlook',
        base: 'outlook',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'to', type: 'csv', valueShape: 'recipient', required: true, doc: 'Comma-separated To recipients' },
          { name: 'cc', type: 'csv', valueShape: 'recipient', required: false, doc: 'Comma-separated Cc recipients' },
          { name: 'bcc', type: 'csv', valueShape: 'recipient', required: false, doc: 'Comma-separated Bcc recipients' },
          { name: 'subject', type: 'string', required: true, doc: 'Message subject' },
          { name: 'body', type: 'string', required: true, doc: 'Message body content' },
          { name: 'body-type', type: 'string', required: false, default: 'Text', doc: 'Body content type, Text or HTML' },
          { name: 'save-to-sent', type: 'boolean', required: false, default: true, doc: 'Save a copy in Sent Items' },
        ],
        bodyTemplate: {
          Message: {
            Subject: '{subject}',
            Body: { ContentType: '{body-type}', Content: '{body}' },
            ToRecipients: '{to}',
            CcRecipients: '{cc}',
            BccRecipients: '{bcc}',
          },
          SaveToSentItems: '{save-to-sent}',
        },
        output: { envelope: envelopeSchema, data: 'Send status' },
        examples: ['mg-api email send --to alice@example.com --subject Hello --body "Hi there"'],
      },
      reply: {
        id: 'email.reply',
        summary: 'Reply to a message via the Outlook REST API',
        method: 'POST',
        path: '/me/messages/{message-id}/reply',
        token: 'outlook',
        base: 'outlook',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'message-id', type: 'string', required: true, doc: 'Source message id' },
          { name: 'comment', type: 'string', required: true, doc: 'Reply comment to prepend to the original body' },
        ],
        bodyTemplate: { Comment: '{comment}' },
        output: { envelope: envelopeSchema, data: 'Reply status' },
        examples: ['mg-api email reply --message-id AAMkAGI... --comment "Thanks, approved"'],
      },
      search: {
        id: 'email.search',
        summary: 'Search messages with KQL-style $search',
        method: 'GET',
        path: '/me/messages',
        token: 'graph',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'query', type: 'string', required: true, doc: 'Search text. Quotes are added automatically' },
          { name: 'top', type: 'number', required: false, default: 25, doc: 'Maximum messages to return' },
        ],
        query: { '$search': '"{query}"', '$top': '{top}' },
        output: { envelope: envelopeSchema, data: 'Search hit collection' },
        examples: ['mg-api email search --query "quarterly review" --top 10'],
      },
      move: {
        id: 'email.move',
        summary: 'Move a message to another mail folder',
        method: 'POST',
        path: '/me/messages/{message-id}/move',
        token: 'graph',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'message-id', type: 'string', required: true, doc: 'Message id' },
          { name: 'destination-folder-id', type: 'string', required: true, doc: 'Destination mail folder id, for example "archive" or a folder id' },
        ],
        bodyTemplate: { destinationId: '{destination-folder-id}' },
        output: { envelope: envelopeSchema, data: 'Moved message' },
        examples: ['mg-api email move --message-id AAMkAGI... --destination-folder-id archive'],
      },
      delete: {
        id: 'email.delete',
        summary: 'Delete a message',
        method: 'DELETE',
        path: '/me/messages/{message-id}',
        token: 'graph',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'message-id', type: 'string', required: true, doc: 'Message id' },
        ],
        output: { envelope: envelopeSchema, data: 'Delete status' },
        examples: ['mg-api email delete --message-id AAMkAGI...'],
      },
      attachments: {
        id: 'email.attachments',
        summary: 'List attachments on a message',
        method: 'GET',
        path: '/me/messages/{message-id}/attachments',
        token: 'graph',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'message-id', type: 'string', required: true, doc: 'Message id' },
        ],
        output: { envelope: envelopeSchema, data: 'Attachment collection' },
        examples: ['mg-api email attachments --message-id AAMkAGI...'],
      },
    },
  },
  calendar: {
    id: 'calendar',
    summary: 'Read and manage Outlook calendar events',
    description: 'List, view, create, update, delete, and RSVP to calendar events, plus find meeting times.',
    verbs: {
      list: {
        id: 'calendar.list',
        summary: 'List calendar events',
        method: 'GET',
        path: '/me/events',
        token: 'graph',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'top', type: 'number', required: false, default: 25, doc: 'Maximum events to return' },
          { name: 'filter', type: 'string', required: false, doc: 'OData $filter expression' },
          { name: 'select', type: 'string', required: false, doc: 'Comma-separated OData $select fields' },
          { name: 'orderby', type: 'string', required: false, doc: 'OData $orderby expression' },
        ],
        query: { '$top': '{top}', '$filter': '{filter}', '$select': '{select}', '$orderby': '{orderby}' },
        output: { envelope: envelopeSchema, data: 'Event collection' },
        examples: ['mg-api calendar list --top 20 --orderby "start/dateTime"'],
      },
      view: {
        id: 'calendar.view',
        summary: 'List events in a time window using calendarView',
        method: 'GET',
        path: '/me/calendarView',
        token: 'graph',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'start', type: 'string', required: true, doc: 'Window start in ISO 8601, for example 2026-01-06T00:00:00Z' },
          { name: 'end', type: 'string', required: true, doc: 'Window end in ISO 8601' },
          { name: 'top', type: 'number', required: false, default: 100, doc: 'Maximum events to return' },
          { name: 'select', type: 'string', required: false, doc: 'Comma-separated OData $select fields' },
        ],
        query: { 'startDateTime': '{start}', 'endDateTime': '{end}', '$top': '{top}', '$select': '{select}' },
        output: { envelope: envelopeSchema, data: 'Event collection within the window' },
        examples: ['mg-api calendar view --start 2026-01-06T00:00:00Z --end 2026-01-07T00:00:00Z --select subject,start,end'],
      },
      get: {
        id: 'calendar.get',
        summary: 'Get a single event by id',
        method: 'GET',
        path: '/me/events/{event-id}',
        token: 'graph',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'event-id', type: 'string', required: true, doc: 'Event id' },
          { name: 'select', type: 'string', required: false, doc: 'Comma-separated OData $select fields' },
        ],
        query: { '$select': '{select}' },
        output: { envelope: envelopeSchema, data: 'Single event' },
        examples: ['mg-api calendar get --event-id AAMkAGI...'],
      },
      create: {
        id: 'calendar.create',
        summary: 'Create a calendar event',
        method: 'POST',
        path: '/me/events',
        token: 'graph',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'subject', type: 'string', required: true, doc: 'Event subject' },
          { name: 'body', type: 'string', required: false, doc: 'Event body content' },
          { name: 'body-type', type: 'string', required: false, default: 'Text', doc: 'Body content type, Text or HTML' },
          { name: 'start', type: 'string', required: true, doc: 'Start in ISO 8601' },
          { name: 'end', type: 'string', required: true, doc: 'End in ISO 8601' },
          { name: 'time-zone', type: 'string', required: false, default: 'UTC', doc: 'IANA time zone for start and end' },
          { name: 'attendees', type: 'csv', valueShape: 'attendee', required: false, doc: 'Comma-separated attendee email addresses' },
          { name: 'location', type: 'string', required: false, doc: 'Display name for the meeting location' },
          { name: 'is-online-meeting', type: 'boolean', required: false, doc: 'Pass true to schedule a Teams meeting' },
        ],
        bodyTemplate: {
          subject: '{subject}',
          body: { contentType: '{body-type}', content: '{body}' },
          start: { dateTime: '{start}', timeZone: '{time-zone}' },
          end: { dateTime: '{end}', timeZone: '{time-zone}' },
          attendees: '{attendees}',
          location: { displayName: '{location}' },
          isOnlineMeeting: '{is-online-meeting}',
        },
        output: { envelope: envelopeSchema, data: 'Created event' },
        examples: ['mg-api calendar create --subject Standup --start 2026-01-15T09:00:00 --end 2026-01-15T09:30:00 --attendees alice@example.com,bob@example.com'],
      },
      update: {
        id: 'calendar.update',
        summary: 'Update event fields',
        method: 'PATCH',
        path: '/me/events/{event-id}',
        token: 'graph',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'event-id', type: 'string', required: true, doc: 'Event id' },
          { name: 'body', type: 'json', required: true, doc: 'JSON object of event fields to update' },
        ],
        output: { envelope: envelopeSchema, data: 'Updated event' },
        examples: ['mg-api calendar update --event-id AAMkAGI... --body \'{"subject":"New title"}\''],
      },
      delete: {
        id: 'calendar.delete',
        summary: 'Delete an event',
        method: 'DELETE',
        path: '/me/events/{event-id}',
        token: 'graph',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'event-id', type: 'string', required: true, doc: 'Event id' },
        ],
        output: { envelope: envelopeSchema, data: 'Delete status' },
        examples: ['mg-api calendar delete --event-id AAMkAGI...'],
      },
      accept: {
        id: 'calendar.accept',
        summary: 'Accept a meeting invitation',
        method: 'POST',
        path: '/me/events/{event-id}/accept',
        token: 'graph',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'event-id', type: 'string', required: true, doc: 'Event id' },
          { name: 'comment', type: 'string', required: false, doc: 'Optional response comment' },
          { name: 'send-response', type: 'boolean', required: false, default: true, doc: 'Send response to the organizer' },
        ],
        bodyTemplate: { comment: '{comment}', sendResponse: '{send-response}' },
        output: { envelope: envelopeSchema, data: 'Accept status' },
        examples: ['mg-api calendar accept --event-id AAMkAGI... --comment "See you there"'],
      },
      decline: {
        id: 'calendar.decline',
        summary: 'Decline a meeting invitation',
        method: 'POST',
        path: '/me/events/{event-id}/decline',
        token: 'graph',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'event-id', type: 'string', required: true, doc: 'Event id' },
          { name: 'comment', type: 'string', required: false, doc: 'Optional response comment' },
          { name: 'send-response', type: 'boolean', required: false, default: true, doc: 'Send response to the organizer' },
        ],
        bodyTemplate: { comment: '{comment}', sendResponse: '{send-response}' },
        output: { envelope: envelopeSchema, data: 'Decline status' },
        examples: ['mg-api calendar decline --event-id AAMkAGI... --comment "Conflict"'],
      },
      'find-times': {
        id: 'calendar.find-times',
        summary: 'Suggest meeting times for a set of attendees',
        method: 'POST',
        path: '/me/findMeetingTimes',
        token: 'graph',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'attendees', type: 'csv', valueShape: 'attendee', required: true, doc: 'Comma-separated attendee email addresses' },
          { name: 'duration', type: 'string', required: false, default: 'PT30M', doc: 'ISO 8601 duration for the meeting, for example PT30M' },
          { name: 'start', type: 'string', required: false, doc: 'Window start in ISO 8601' },
          { name: 'end', type: 'string', required: false, doc: 'Window end in ISO 8601' },
          { name: 'time-zone', type: 'string', required: false, default: 'UTC', doc: 'IANA time zone for the time constraint' },
        ],
        bodyTemplate: {
          attendees: '{attendees}',
          meetingDuration: '{duration}',
          timeConstraint: {
            timeslots: [
              {
                start: { dateTime: '{start}', timeZone: '{time-zone}' },
                end: { dateTime: '{end}', timeZone: '{time-zone}' },
              },
            ],
          },
        },
        output: { envelope: envelopeSchema, data: 'Meeting time suggestions' },
        examples: ['mg-api calendar find-times --attendees alice@example.com,bob@example.com --duration PT30M --start 2026-01-15T09:00:00 --end 2026-01-15T17:00:00'],
      },
    },
  },
  teams: {
    id: 'teams',
    summary: 'Work with Microsoft Teams teams and channels',
    description: 'List joined teams, inspect channels, and post channel messages.',
    verbs: {
      'list-joined': {
        id: 'teams.list-joined',
        summary: 'List Teams the signed-in user has joined',
        method: 'GET',
        path: '/me/joinedTeams',
        token: 'graph',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [],
        output: { envelope: envelopeSchema, data: 'Joined team collection' },
        examples: ['mg-api teams list-joined'],
      },
      'list-channels': {
        id: 'teams.list-channels',
        summary: 'List channels for a team',
        method: 'GET',
        path: '/teams/{team-id}/channels',
        token: 'chat',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'team-id', type: 'string', required: true, doc: 'Team id' },
        ],
        output: { envelope: envelopeSchema, data: 'Channel collection' },
        examples: ['mg-api teams list-channels --team-id 12345678-...'],
      },
      'send-channel-message': {
        id: 'teams.send-channel-message',
        summary: 'Send a message to a Teams channel',
        method: 'POST',
        path: '/teams/{team-id}/channels/{channel-id}/messages',
        token: 'chat',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'team-id', type: 'string', required: true, doc: 'Team id' },
          { name: 'channel-id', type: 'string', required: true, doc: 'Channel id' },
          { name: 'content', type: 'string', required: true, doc: 'Message content' },
          { name: 'content-type', type: 'string', required: false, default: 'text', doc: 'Message content type, text or html' },
        ],
        bodyTemplate: { body: { contentType: '{content-type}', content: '{content}' } },
        output: { envelope: envelopeSchema, data: 'Created channel message' },
        examples: ['mg-api teams send-channel-message --team-id ... --channel-id ... --content "Build passed"'],
      },
    },
  },
  chats: {
    id: 'chats',
    summary: 'Work with Teams 1:1 and group chats',
    description: 'List chats, read chat messages, and send chat messages.',
    verbs: {
      list: {
        id: 'chats.list',
        summary: 'List Teams chats',
        method: 'GET',
        path: '/me/chats',
        token: 'outlook',
        base: 'outlook',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'top', type: 'number', required: false, default: 20, doc: 'Maximum chats to return' },
        ],
        query: { '$top': '{top}' },
        output: { envelope: envelopeSchema, data: 'Chat collection' },
        examples: ['mg-api chats list --top 20'],
      },
      messages: {
        id: 'chats.messages',
        summary: 'List messages in a chat',
        method: 'GET',
        path: '/me/chats/{chat-id}/messages',
        token: 'outlook',
        base: 'outlook',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'chat-id', type: 'string', required: true, doc: 'Chat id' },
          { name: 'top', type: 'number', required: false, default: 50, doc: 'Maximum messages to return' },
        ],
        query: { '$top': '{top}' },
        output: { envelope: envelopeSchema, data: 'Chat message collection' },
        examples: ['mg-api chats messages --chat-id 19:... --top 50'],
      },
      send: {
        id: 'chats.send',
        summary: 'Send a message to a chat',
        method: 'POST',
        path: '/chats/{chat-id}/messages',
        token: 'chat',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'chat-id', type: 'string', required: true, doc: 'Chat id' },
          { name: 'content', type: 'string', required: true, doc: 'Message content' },
          { name: 'content-type', type: 'string', required: false, default: 'text', doc: 'Message content type, text or html' },
        ],
        bodyTemplate: { body: { contentType: '{content-type}', content: '{content}' } },
        output: { envelope: envelopeSchema, data: 'Created chat message' },
        examples: ['mg-api chats send --chat-id 19:... --content "Hello"'],
      },
    },
  },
  users: {
    id: 'users',
    summary: 'Look up users and people',
    description: 'Read the signed-in user profile, search the org people index, and fetch user profiles by id.',
    verbs: {
      me: {
        id: 'users.me',
        summary: 'Get the signed-in user profile',
        method: 'GET',
        path: '/me',
        token: 'graph',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'select', type: 'string', required: false, doc: 'Comma-separated OData $select fields' },
        ],
        query: { '$select': '{select}' },
        output: { envelope: envelopeSchema, data: 'Signed-in user profile' },
        examples: ['mg-api users me --select displayName,mail,jobTitle,department'],
      },
      search: {
        id: 'users.search',
        summary: 'Search the org people index. Use scoredEmailAddresses for email lookup',
        method: 'GET',
        path: '/me/people',
        token: 'graph',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'query', type: 'string', required: true, doc: 'Search text. Quotes are added automatically' },
          { name: 'top', type: 'number', required: false, default: 10, doc: 'Maximum people to return' },
          { name: 'select', type: 'string', required: false, default: 'displayName,scoredEmailAddresses,jobTitle', doc: 'Comma-separated OData $select fields. emailAddresses is not a supported person property; use scoredEmailAddresses' },
        ],
        query: { '$search': '"{query}"', '$top': '{top}', '$select': '{select}' },
        output: { envelope: envelopeSchema, data: 'People collection' },
        examples: ['mg-api users search --query "Martinez" --top 5'],
      },
      get: {
        id: 'users.get',
        summary: 'Get a user profile by id, UPN, or email',
        method: 'GET',
        path: '/users/{user-id}',
        token: 'graph',
        base: 'graph',
        auth: 'required',
        handler: 'graph-rest',
        params: [
          { name: 'user-id', type: 'string', required: true, doc: 'User id, UPN, or email' },
          { name: 'select', type: 'string', required: false, doc: 'Comma-separated OData $select fields' },
        ],
        query: { '$select': '{select}' },
        output: { envelope: envelopeSchema, data: 'User profile' },
        examples: ['mg-api users get --user-id alice@example.com --select displayName,jobTitle'],
      },
    },
  },
  schema: {
    id: 'schema',
    summary: 'Inspect the generated Microsoft Graph capability schema',
    description: 'Return the machine-readable contract that also generates help and the skill router.',
    verbs: {
      show: {
        id: 'schema.show',
        summary: 'Show all capabilities or one capability/verb contract',
        method: 'LOCAL',
        auth: 'none',
        handler: 'schema',
        params: [
          { name: 'capability', type: 'string', required: false, doc: 'Capability id, for example email or calendar' },
          { name: 'verb', type: 'string', required: false, doc: 'Verb id within the capability' },
        ],
        output: { envelope: envelopeSchema, data: 'Capability schema' },
        examples: ['mg-api schema', 'mg-api schema email send'],
      },
    },
  },
  doctor: {
    id: 'doctor',
    summary: 'Run local health checks for the agentic CLI',
    description: 'Verify Node.js compatibility and the cached auth file.',
    verbs: {
      run: {
        id: 'doctor.run',
        summary: 'Run health checks',
        method: 'LOCAL',
        auth: 'none',
        handler: 'doctor',
        params: [],
        output: { envelope: envelopeSchema, data: 'Health-check results' },
        examples: ['mg-api doctor'],
      },
    },
  },
  update: {
    id: 'update',
    summary: 'Self-update this mg-api checkout',
    description: 'Pull latest source, install dependencies, and run the build validation for git-clone installs.',
    verbs: {
      run: {
        id: 'update.run',
        summary: 'Self-update from the current git clone',
        method: 'LOCAL',
        auth: 'none',
        handler: 'self-update',
        params: [],
        output: { envelope: envelopeSchema, data: 'Update steps and status' },
        examples: ['mg-api update'],
      },
    },
  },
};

const plannedCapabilities = {
  email: ['folders', 'large-attach', 'reply-all', 'forward'],
  calendar: ['instances', 'occurrences'],
  teams: ['members', 'list-team'],
  chats: ['get', 'members'],
  users: ['list', 'photo'],
  files: ['list', 'get', 'upload', 'download'],
};

module.exports = { capabilities, plannedCapabilities, envelopeSchema };
